import React, { useState } from 'react';
import {
  ShieldAlert,
  ShieldCheck,
  Play,
  Pause,
  Radio,
  Sparkles,
  Volume2,
  Activity,
  AlertTriangle,
  ArrowDown,
  CheckCircle2,
} from 'lucide-react';
import { WaveformVisualizer } from '../common/WaveformVisualizer';
import { VoiceVerdict } from '../../types';

interface HeroSectionProps {
  onScrollToScanner: () => void;
  onQuickTestSample: (type: VoiceVerdict) => void;
  onOpenHowItWorks: () => void;
  isAnalyzing: boolean;
}

export const HeroSection: React.FC<HeroSectionProps> = ({
  onScrollToScanner,
  onQuickTestSample,
  onOpenHowItWorks,
  isAnalyzing,
}) => {
  const [isPlayingPreview, setIsPlayingPreview] = useState(false);
  const [activePreviewType, setActivePreviewType] = useState<'real' | 'cloned'>('cloned');

  const togglePreview = (type: 'real' | 'cloned') => {
    setActivePreviewType(type);
    setIsPlayingPreview(!isPlayingPreview || activePreviewType !== type);
  };

  return (
    <section className="relative w-full overflow-hidden pt-4 pb-12 sm:pt-6 sm:pb-16 border-b border-[#1F293D]/80">
      {/* Background radial ambient lights inspired by VoxClone reference */}
      <div className="absolute top-1/4 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] sm:w-[900px] h-[400px] bg-gradient-to-b from-[#38BDF8]/10 via-[#B5384F]/10 to-transparent blur-3xl pointer-events-none -z-10" />
      <div className="absolute top-10 right-10 w-72 h-72 bg-[#2E9E5B]/10 blur-3xl pointer-events-none -z-10" />

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-10 lg:gap-8 items-center">
          {/* Left Column: Headline & Value Proposition (7 cols) */}
          <div className="lg:col-span-7 flex flex-col items-start text-left">
            {/* Top pill badge */}
            <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-slate-900/90 border border-slate-700/80 text-xs font-mono text-slate-300 mb-6 shadow-inner">
              <span className="w-2 h-2 rounded-full bg-[#B5384F] animate-ping" />
              <span className="text-[#38BDF8] font-bold">2026 Threat Shield:</span>
              <span>AI Voice Lie Detector</span>
            </div>

            {/* Main Headline */}
            <h1 className="text-4xl sm:text-5xl lg:text-6xl font-extrabold text-white tracking-tight leading-[1.1]">
              Detect Any Voice Clone{' '}
              <span className="text-transparent bg-clip-text bg-gradient-to-r from-[#2E9E5B] via-emerald-400 to-[#38BDF8]">
                with Human-Level Realism Instantly
              </span>
            </h1>

            {/* Rich problem & solution description */}
            <p className="mt-5 text-sm sm:text-base text-slate-300 leading-relaxed max-w-2xl">
              In 2026, cybercriminals can clone your voice in seconds from a 10–30s YouTube clip or Instagram reel to impersonate kids in emergency calls (<em className="text-rose-300">&ldquo;Mom, I&apos;ve been in an accident, send money now&rdquo;</em>), spoof CEOs commanding wire transfers, or steal bank OTPs.
            </p>

            <p className="mt-3 text-sm sm:text-base text-slate-400 leading-relaxed max-w-2xl">
              <strong className="text-white">Sonara is the AI voice lie detector:</strong> analyzing acoustic biomarkers and vocoder phase artifacts in real time to reveal whether an incoming call was spoken by a real human or generated by an AI clone.
            </p>

            {/* CTA Buttons */}
            <div className="mt-8 flex flex-wrap items-center gap-4">
              <button
                type="button"
                onClick={onScrollToScanner}
                className="flex items-center gap-2 px-6 py-3.5 bg-gradient-to-r from-[#2E9E5B] to-[#1F7542] hover:from-[#35b568] hover:to-[#24874c] text-white font-bold text-sm rounded-xl shadow-lg shadow-[#2E9E5B]/25 hover:shadow-[#2E9E5B]/40 transition-all hover:scale-[1.02] active:scale-[0.98]"
              >
                <Radio className="w-4 h-4 text-white" />
                <span>Start Voice Scan</span>
              </button>

              <button
                type="button"
                onClick={onOpenHowItWorks}
                className="flex items-center gap-2 px-5 py-3.5 bg-slate-900/90 hover:bg-slate-800 text-slate-200 border border-slate-700/80 font-semibold text-sm rounded-xl transition-colors"
              >
                <Play className="w-4 h-4 text-[#38BDF8] fill-[#38BDF8]" />
                <span>How It Works</span>
              </button>
            </div>
          </div>

          {/* Right Column: Interactive Cyber Console (5 cols) matching VoxClone reference */}
          <div className="lg:col-span-5 flex flex-col items-center justify-center relative">
            {/* Outer console frame */}
            <div className="w-full max-w-md bg-gradient-to-b from-[#161F30] via-[#111827] to-[#0B0F17] border border-[#1F293D] rounded-3xl p-6 shadow-2xl relative overflow-hidden group">
              {/* Top status header */}
              <div className="flex items-center justify-between pb-4 mb-4 border-b border-[#1F293D]/80">
                <div className="flex items-center gap-2">
                  <span className="w-2.5 h-2.5 rounded-full bg-[#38BDF8] animate-pulse" />
                  <span className="text-xs font-mono font-bold tracking-wider uppercase text-slate-300">
                    Acoustic Lie-Detector Unit
                  </span>
                </div>
                <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-slate-800 text-[#38BDF8] border border-slate-700">
                  REAL-TIME 2026
                </span>
              </div>

              {/* The Reference Dual Switches: Safe Green vs Cloned Red button */}
              <div className="grid grid-cols-2 gap-3 mb-5">
                {/* SAFE / REAL BUTTON */}
                <button
                  type="button"
                  onClick={() => {
                    togglePreview('real');
                    onQuickTestSample('Real');
                  }}
                  disabled={isAnalyzing}
                  className="flex flex-col items-center justify-center p-4 rounded-2xl bg-gradient-to-b from-[#0F2218] to-[#08150E] border-2 border-[#2E9E5B]/60 hover:border-[#2E9E5B] shadow-lg shadow-[#2E9E5B]/20 transition-all group/btn active:scale-95 text-center"
                  title="Test an authentic biological human voice sample"
                >
                  <div className="w-12 h-12 rounded-full bg-[#2E9E5B] flex items-center justify-center shadow-md shadow-[#2E9E5B]/50 mb-2.5 group-hover/btn:scale-105 transition-transform">
                    <CheckCircle2 className="w-6 h-6 text-slate-900 stroke-[2.5]" />
                  </div>
                  <span className="text-xs font-bold text-white uppercase tracking-wider">
                    Real Voice
                  </span>
                  <span className="text-[10px] text-emerald-400 font-mono mt-0.5">
                    99.1% Biological
                  </span>
                </button>

                {/* CLONED / DANGER BUTTON */}
                <button
                  type="button"
                  onClick={() => {
                    togglePreview('cloned');
                    onQuickTestSample('Cloned');
                  }}
                  disabled={isAnalyzing}
                  className="flex flex-col items-center justify-center p-4 rounded-2xl bg-gradient-to-b from-[#250F14] to-[#14070A] border-2 border-[#B5384F]/60 hover:border-[#B5384F] shadow-lg shadow-[#B5384F]/20 transition-all group/btn active:scale-95 text-center"
                  title="Test an AI synthesized voice clone sample"
                >
                  <div className="w-12 h-12 rounded-full bg-[#B5384F] flex items-center justify-center shadow-md shadow-[#B5384F]/50 mb-2.5 group-hover/btn:scale-105 transition-transform">
                    <AlertTriangle className="w-6 h-6 text-white stroke-[2.5]" />
                  </div>
                  <span className="text-xs font-bold text-white uppercase tracking-wider">
                    Cloned Voice
                  </span>
                  <span className="text-[10px] text-rose-300 font-mono mt-0.5">
                    98.4% Synthetic
                  </span>
                </button>
              </div>

              {/* Live Audio Monitor Card (inspired by left audio card in reference image) */}
              <div className="bg-[#0B0F17] border border-[#1F293D] rounded-2xl p-4 flex flex-col gap-3">
                <div className="flex items-center justify-between text-xs">
                  <div className="flex items-center gap-2">
                    <span className="font-semibold text-white font-mono">
                      {activePreviewType === 'cloned' ? 'Emergency_Kid_Scam.wav' : 'Authentic_Caller_Checkin.wav'}
                    </span>
                  </div>
                  <span
                    className={`font-mono font-bold text-[10px] px-2 py-0.5 rounded ${
                      activePreviewType === 'cloned'
                        ? 'bg-[#B5384F]/20 text-rose-300 border border-[#B5384F]/30'
                        : 'bg-[#2E9E5B]/20 text-emerald-300 border border-[#2E9E5B]/30'
                    }`}
                  >
                    {activePreviewType === 'cloned' ? 'AI CLONE ⚠️' : 'HUMAN ✅'}
                  </span>
                </div>

                {/* Animated Waveform Visualizer & Level Meter */}
                <div className="flex items-center gap-3">
                  <div className="flex-1">
                    <WaveformVisualizer
                      isPlaying={true}
                      color={activePreviewType === 'cloned' ? '#B5384F' : '#2E9E5B'}
                      barsCount={26}
                      height={32}
                    />
                  </div>

                  {/* Vertical Volume Meter (like in reference image) */}
                  <div className="flex items-end gap-1 h-8 px-2 py-1 bg-slate-900 rounded-lg border border-slate-800">
                    <div className="w-1.5 bg-[#2E9E5B] h-[65%] rounded-sm" />
                    <div className="w-1.5 bg-[#F59E0B] h-[85%] rounded-sm" />
                    <div className="w-1.5 bg-[#B5384F] h-[40%] rounded-sm" />
                  </div>
                </div>

                <div className="flex items-center justify-between text-[11px] text-slate-400 pt-1 border-t border-slate-800/80">
                  <span>Spectral Vocoder Scan: Active</span>
                  <span className="font-mono text-slate-300">Latency: 0.8s</span>
                </div>
              </div>

              {/* Quick instruction hint */}
              <p className="text-[11px] text-center text-slate-400 mt-3 font-mono">
                Click green or red button above to simulate live voice classification
              </p>
            </div>
          </div>
        </div>

        {/* Bottom Feature Strip (matching reference image footer strip) */}
        <div className="mt-12 pt-8 border-t border-[#1F293D]/80">
          <div className="bg-[#111827]/70 border border-[#1F293D] rounded-2xl p-4 sm:p-5">
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4 sm:gap-6 divide-y sm:divide-y-0 sm:divide-x divide-[#1F293D]">
              <div className="flex flex-col items-center sm:items-start text-center sm:text-left px-2">
                <span className="text-xs sm:text-sm font-bold text-white">
                  Real-Time Detection
                </span>
                <span className="text-[11px] text-slate-400 mt-0.5">
                  &lt;1.2s inference on FastAPI
                </span>
              </div>

              <div className="flex flex-col items-center sm:items-start text-center sm:text-left px-2 pt-3 sm:pt-0">
                <span className="text-xs sm:text-sm font-bold text-white">
                  10–30s Audio Fingerprint
                </span>
                <span className="text-[11px] text-slate-400 mt-0.5">
                  Micro-breath & pitch analysis
                </span>
              </div>

              <div className="flex flex-col items-center sm:items-start text-center sm:text-left px-2 pt-3 sm:pt-0">
                <span className="text-xs sm:text-sm font-bold text-white">
                  Scam Prevention
                </span>
                <span className="text-[11px] text-slate-400 mt-0.5">
                  Family emergency & wire fraud
                </span>
              </div>

              <div className="flex flex-col items-center sm:items-start text-center sm:text-left px-2 pt-3 sm:pt-0">
                <span className="text-xs sm:text-sm font-bold text-white">
                  100% In-Memory Analysis
                </span>
                <span className="text-[11px] text-slate-400 mt-0.5">
                  Zero biometric voice retention
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};
